services:
  - type: web
    name: fas-front-app
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    plan: free  # ou escolha outro plano disponível
